### ISSUE TITLE
I can install the service

### ISSUE THREAD

**Issue by peregrine-software** [peregrine-software/windows-metered-connection#4]
Very basic initial installer

On a Windows 10 machine,
as an administrator on the machine,
I can run the "Metered Connection Scheduler.msi" file.

I will be shown a simple GUI to accept license and install.
After install the service will be installed and start.
I can see it in the Services management app, and stop and start it.

I can uninstall Metered Connection Scheduler from 'Apps & features' (aka Add & Remove Programs)

**Comment by darynmitchell** [comment]
Done by cf9e0fb and d5f8e80 (with f7dbe29 thrown in for good measure)
